CREATE DATABASE AIRLINES
ON PRIMARY(
NAME='AIRLINES_MAIN',
FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AIRLINES_MAIN.mdf',
SIZE=10MB,
MAXSIZE=20MB,
FILEGROWTH=1MB
),
FILEGROUP AIRLINES_SEC
(NAME='AIRLINES_SEC',
FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AIRLINES_SEC.ndf',
SIZE=10MB,
MAXSIZE=20MB,
FILEGROWTH=1MB
)
LOG ON(
NAME='AIRLINES_LOG',
FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AIRLINES_LOG.ldf',
SIZE=10MB,
MAXSIZE=20MB,
FILEGROWTH=1MB
)
GO
USE AIRLINES
/*
COUNTRY
STATES
CITY
REGION
CITE
ADDRESS
BANK
*/
CREATE TABLE COUNTRY
(CountryId SMALLINT PRIMARY KEY,
CountryName VARCHAR(50))

GO

CREATE TABLE STATES
(StateId INT PRIMARY KEY,
StateName VARCHAR(50))

GO

CREATE TABLE CITY
(CityId INT PRIMARY KEY,
CityName VARCHAR(50))

GO

CREATE TABLE CITE
(CiteId TINYINT PRIMARY KEY,
CiteName VARCHAR(50))

GO

CREATE TABLE REGION
(RegionId TINYINT PRIMARY KEY,
RegionName VARCHAR(50))

GO

use AIRLINES
GO
CREATE TABLE ADDRESS
(AddressID INT PRIMARY KEY,
Flat_no VARCHAR(50), 
Locality VARCHAR(100),
CityID INT,
StateID INT,
RegionId TINYINT,
CountryID SMALLINT,
Pincode VARCHAR(10),
FOREIGN KEY (CityId) REFERENCES City(cityid),
FOREIGN KEY (StateId) REFERENCES States(StateId),
FOREIGN KEY (RegionId) REFERENCES Region(Regionid),
FOREIGN KEY (CountryId) REFERENCES Country(CountryId))

GO

use AIRLINES
CREATE TABLE BANK(
	BankId INT Primary Key,
	Bank_Name Varchar(100),
	Branch_Name VARCHAR(200),
	AddressId INT,
	IFSC_CODE NVARCHAR(100),
	FOREIGN KEY (AddressId) REFERENCES [ADDRESS](AddressId)
	)

GO

/*
CUSTOMER PERSONAL
CUSTOMER EMERGENCY
PARENTS
CUSTOMER ACCOUNT
CUSTOMER MAIN
*/
CREATE TABLE CUSTOMER_PERSONAL(
	CustomerId INT PRIMARY KEY,
	Fname VARCHAR(100),
	Mname VARCHAR(100),
	Lname VARCHAR(100),
	GENDER CHAR(1),
	PhoneNo NVARCHAR(20),
	EmailId NVARCHAR(200),
	AddressId INT,
	Photo VARBINARY(MAX),
	ThumbPrint VARBINARY(MAX)
	FOREIGN KEY (addressId) REFERENCES [Address](addressId))

GO

CREATE TABLE CUSTOMER_EMG
(EMG_Id INT PRIMARY KEY,
	Fname VARCHAR(100),
	Mname VARCHAR(100),
	Lname VARCHAR(100),
	PhoneNo NVARCHAR(20),
	EmailId NVARCHAR(200),
	Relation VARCHAR (100),
	AddressId INT,
	FOREIGN KEY (addressId) REFERENCES [Address](addressId))

GO

CREATE TABLE PARENTS(
Parent_Id INT PRIMARY KEY,
	Father_name VARCHAR(100),
	Mother_name VARCHAR(100),
	PhoneNo NVARCHAR(20),
	EmailId NVARCHAR(200),
	AddressId INT,
	FOREIGN KEY (addressId) REFERENCES [Address](addressId))

GO

CREATE TABLE CUSTOMER_ACCOUNT(
	ACC_NO INT PRIMARY KEY,
	BankId INT,
	CARD_NO NVARCHAR(16),
	CARD_EXPIRY DATE,
	FOREIGN KEY (BankId) REFERENCES BANK(BANKID))

GO
CREATE TABLE CUSTOMER_MAIN(
	CustomerId INT PRIMARY KEY,
	PASSPORT_NO NVARCHAR(50),
	Parent_Id INT,
	EMG_Id INT,
	ACC_NO INT,
	FOREIGN KEY (Parent_Id) REFERENCES PARENTS(Parent_Id),
	FOREIGN KEY (EMG_Id) REFERENCES CUSTOMER_EMG(EMG_Id),
	FOREIGN KEY (ACC_NO) REFERENCES CUSTOMER_ACCOUNT(ACC_NO)
	)
GO
ALTER TABLE CUSTOMER_PERSONAL
ADD FOREIGN KEY (CustomerId) REFERENCES CUSTOMER_MAIN(CustomerId)

GO

/*
AIRLINE
AIRPORT
AIRCRAFT
AIRLINE AIRCRAFT REL.
JOURNEY
SCHEDULE
*/
CREATE TABLE AIRLINE(
	AirlineId INT PRIMARY KEY,
	Airline_Name VARCHAR(200))

CREATE TABLE AIRPORT(
	AirportId INT PRIMARY KEY,
	AirportName NVARCHAR(200),
	AddressId INT,
	FOREIGN KEY (AddressId) REFERENCES ADDRESS(AddressId))

GO

CREATE TABLE AIRCRAFT(
	Aircraft_ID INT PRIMARY KEY,
	Aircraft_NAME NVARCHAR(200),
	Seating_Capacity SmallINT,
	[Description] VARBINARY(MAX))

GO

CREATE TABLE AIRLINE_AIRCRAFT(
	AirlineId INT,
	Aircraft_Id INT,
	FOREIGN KEY (AirlineId) REFERENCES AIRLINE(AirlineId),
	FOREIGN KEY (Aircraft_Id) REFERENCES AIRCRAFT(Aircraft_Id))

GO

CREATE TABLE JOURNEY(
	JourneyId INT PRIMARY KEY,
	OriginId Int,
	DestinationId Int,
	Stops TINYINT,
	FOREIGN KEY (OriginId) REFERENCES Airport(AirportId),
	FOREIGN KEY (DestinationId) REFERENCES Airport(AirportId))
ALTER TABLE JOURNEY
ADD Time_Duration nvarchar(50)
GO

CREATE TABLE SCHEDULE(
	ScheduleId INT PRIMARY KEY,
	JourneyId INT,
	Date_Time Datetime2,
	FOREIGN KEY (JourneyId) REFERENCES JOURNEY(JourneyId))

GO

/*
PILOT PERSONAL
PILOT EMG
PILOT ACCOUNT
PILOT MAIN
*/
CREATE TABLE PILOT_PERSONAL(
	PilotId INT PRIMARY KEY,
	Fname VARCHAR(100),
	Mname VARCHAR(100),
	Lname VARCHAR(100),
	GENDER CHAR(1),
	PhoneNo NVARCHAR(20),
	EmailId NVARCHAR(200),
	AddressId INT,
	Photo VARBINARY(MAX),
	ThumbPrint VARBINARY(MAX)
	FOREIGN KEY (addressId) REFERENCES [Address](addressId),
	);

GO

CREATE TABLE PILOT_EMG
(EMG_Id INT PRIMARY KEY,
	Fname VARCHAR(100),
	Mname VARCHAR(100),
	Lname VARCHAR(100),
	PhoneNo NVARCHAR(20),
	EmailId NVARCHAR(200),
	Relation VARCHAR (100),
	AddressId INT,
	FOREIGN KEY (addressId) REFERENCES [Address](addressId))

GO

CREATE TABLE PILOT_ACCOUNT(
	ACC_NO INT PRIMARY KEY,
	BankId INT,
	CARD_NO NVARCHAR(16),
	CARD_EXPIRY DATE,
	FOREIGN KEY (BankId) REFERENCES BANK(BANKID))

GO

CREATE TABLE PILOT_MAIN(
	PilotId INT PRIMARY KEY,
	LicenseNo nVarchar(100),
	Parent_Id INT,
	EMG_Id INT,
	ACC_NO INT,
	FOREIGN KEY (Parent_Id) REFERENCES PARENTS(Parent_Id),
	FOREIGN KEY (EMG_Id) REFERENCES PILOT_EMG(EMG_Id),
	FOREIGN KEY (ACC_NO) REFERENCES PILOT_ACCOUNT(ACC_NO),
	FOREIGN KEY (PilotId) REFERENCES PILOT_PERSONAL(PilotId)
	)

GO

/*
FLIGHT DETAILS
FLIGHT CLASS
CUSTOMER TRANSACTION
RESERVATION
BORADING PASS
BAGGAGE
*/

CREATE TABLE FLIGHT_DETAILS(
	FlightId INT PRIMARY KEY,
	ScheduleId INT,
	Flight_Status Varchar(20),--Cancelled,etc.
	PilotId INT,
	Aircraft_Id INT,
	Seats_Booked SMALLINT,
	FOREIGN KEY (ScheduleId) REFERENCES SCHEDULE(ScheduleId),
	FOREIGN KEY (PilotId) REFERENCES PILOT_MAIN(PilotId),
	FOREIGN KEY (Aircraft_Id) REFERENCES AIRCRAFT(Aircraft_Id))

GO
CREATE TABLE FLIGHT_CLASS(
	ClassId TinyInt PRIMARY KEY,
	Class_Name Varchar(20))

GO

CREATE TABLE CUSTOMER_TRANSACTION(
	TransactionId INT PRIMARY KEY,
	CustomerId INT,
	FlightId INT,
	ClassId TINYINT,
	Transaction_Date DATE,
	Transaction_Status varchar(20),
	FOREIGN KEY (ClassId) REFERENCES FLIGHT_CLASS(ClassID),
	FOREIGN KEY (CustomerID) REFERENCES CUSTOMER_MAIN(CustomerID),
	FOREIGN KEY (FlightId) REFERENCES FLIGHT_DETAILS(FlightId))
ALTER TABLE CUSTOMER_TRANSACTION
ADD AMOUNT MONEY

GO

CREATE TABLE RESERVATION(
	ReservationId INT PRIMARY KEY,
	CustomerID INT,
	FlightId INT,
	TransactionId INT,
	Booking_Date Date,
	Reservation_Status Varchar(20),
	FOREIGN KEY (CustomerId) REFERENCES Customer_Main(CustomerId),
	FOREIGN KEY (FlightId) REFERENCES FLIGHT_DETAILS(FlightId),
	FOREIGN KEY (TransactionId) REFERENCES CUSTOMER_TRANSACTION(TransactionId))

GO

CREATE TABLE BOARDING_PASS(
	PassId INT PRIMARY KEY,
	CustomerId INT,
	ReservationId INT,
	SeatNo TINYINT,
	Boarding_Date DATE
	FOREIGN KEY (CustomerID) REFERENCES CUSTOMER_MAIN(CustomerID),
	FOREIGN KEY (ReservationID) REFERENCES RESERVATION(ReservationID))

GO

CREATE TABLE BAGGAGE(
	BaggageId INT PRIMARY KEY,
	CustomerId INT,
	Baggage_Weight TinyINT,
	Baggage_Type VARCHAR(50),--HANDBAG,PURSE,TROLLEY-BAG,SUITCASE,ETC.
	FlightId INT,
	FOREIGN KEY (CustomerID) REFERENCES CUSTOMER_MAIN(CustomerID),
	FOREIGN KEY (FlightId) REFERENCES Flight_Details(FlightId))

GO



/*DEPARTMENT
DESIGNATION
EMPLOYEE
EMPLOYEE PERSONAL
EMPLOYEE EDUCATION
EMPLOYEE PARENTS
EMPLOYEE MEDICAL
EMPLOYEE EMERGENCY
EMPLOYEE LEAVE
EMPLOYEE ATTENDANCE
EMPLOYEE PERFORMANCE
EMPLOYEE SALARY
EMPLOYEE AIRPORT(AIRPORT,DEPT,DESIG,EMP)
*/

CREATE TABLE DEPARTMENT(
	DeptId Int PRIMARY KEY,
	DeptName varchar(20))

GO

CREATE TABLE DESIGNATION(
	DESIGNATION_ID INT PRIMARY KEY,
	Desig_Name VARCHAR(20))

GO

CREATE TABLE GRADE_PAY(
	PayId INT PRIMARY KEY,
	DESIGNATION_ID INT,
	BASIC_PAY MONEY
	FOREIGN KEY (DESIGNATION_ID) REFERENCES DESIGNATION(DESIGNATION_ID))

GO

CREATE TABLE EMP_PERSONAL(
	EMPId INT PRIMARY KEY,
	Fname VARCHAR(100),
	Mname VARCHAR(100),
	Lname VARCHAR(100),
	GENDER CHAR(1),
	PhoneNo NVARCHAR(20),
	EmailId NVARCHAR(200),
	AddressId INT,
	Photo VARBINARY(MAX),
	ThumbPrint VARBINARY(MAX)
	FOREIGN KEY (addressId) REFERENCES [Address](addressId),
	);

GO

CREATE TABLE EMP_MEDICAL(
	MedicalId INT PRIMARY KEY,
	Health_Status VARCHAR(20),
	Condition VARchAR(200),
	Cond_Description NVARCHAR(250)
	)


GO

CREATE TABLE EMP_EMG
(EMG_Id INT PRIMARY KEY,
	Fname VARCHAR(100),
	Mname VARCHAR(100),
	Lname VARCHAR(100),
	PhoneNo NVARCHAR(20),
	EmailId NVARCHAR(200),
	Relation VARCHAR (100),
	AddressId INT,
	FOREIGN KEY (addressId) REFERENCES [Address](addressId))

GO

CREATE TABLE EMP_ACCOUNT(
	ACC_NO INT PRIMARY KEY,
	BankId INT,
	CARD_NO NVARCHAR(16),
	CARD_EXPIRY DATE,
	FOREIGN KEY (BankId) REFERENCES BANK(BANKID))

GO

CREATE TABLE COURSE(
	CourseId INT PRIMARY KEY,
	Course_Name NVARCHAR(200),--10TH,12TH,B.TECH,B.A,M.A,ETC
	Specialization NVARCHAR(200),--ARTS,MEDICAL,ENGINEERING,ETC
	Duration TINYINT)
Go

CREATE TABLE EMP_EDUCATION(
	Education_Id INT PRIMARY KEY,
	Highest_Edu INT,
	Tenth_Cert VARBINARY(MAX),
	Twelfth_Cert VARBINARY(MAX),
	Diploma_Cert VARBINARY(MAX),
	UnderGrad_Cert VARBINARY(MAX),
	PostGrad_Cert VARBINARY(MAX),
	Phd_Cert VARBINARY(MAX))
ALTER TABLE EMP_EDUCATION
ADD FOREIGN KEY (Highest_Edu) REFERENCES COURSE(CourseId)
GO

CREATE TABLE EMP_MAIN(
	EMPId INT PRIMARY KEY,
	Parent_Id INT,
	MedicalId INT,
	EMG_Id INT,
	ACC_NO INT,
	Education_Id INT,
	FOREIGN KEY (Parent_Id) REFERENCES PARENTS(Parent_Id),
	FOREIGN KEY (MedicalId) REFERENCES EMP_MEDICAL(MedicalId),
	FOREIGN KEY (EMG_Id) REFERENCES EMP_EMG(EMG_Id),
	FOREIGN KEY (ACC_NO) REFERENCES EMP_ACCOUNT(ACC_NO),
	FOREIGN KEY (Education_Id) REFERENCES EMP_EDUCATION(Education_Id),
	)
ALTER TABLE EMP_MAIN
ADD FOREIGN KEY (EMPID) REFERENCES EMP_PERSONAL(EMPID)
GO

CREATE TABLE LEAVE_MASTER(
	LeaveId INT PRIMARY KEY,
	Leave_Type Varchar(20))

GO

CREATE TABLE EMP_LEAVE(
	EMPID INT,
	LeaveId INT,
	Leave_Date Date,
	FOREIGN KEY (EMPId) REFERENCES EMP_PERSONAL(EMPId),
	FOREIGN KEY (LeaveId) REFERENCES LEAVE_MASTER(LeaveId))

GO

CREATE TABLE EMP_ATTENDANCE(
	EMPID INT,
	ATT_DATE DATE,
	ATT_Status Varchar(10),--absent, present
	FOREIGN KEY (EMPId) REFERENCES EMP_PERSONAL(EMPId))

GO

CREATE TABLE EMP_PERFORMANCE(
	EMPID INT,
	Rating Decimal(2,1),
	Fin_Year_Start SMALLINT,
	Fin_Year_End SMALLINT,
	FOREIGN KEY (EMPId) REFERENCES EMP_PERSONAL(EMPId))

GO

CREATE TABLE EMP_SALARY(
	Transaction_ID INT PRIMARY KEY,
	FIN_YEAR_START INT,
	QUATER NCHAR(1),
	Transaction_Date Date,
	EMPID INT,
	PayId INT,
	AMOUNT MONEY,
	Transaction_status Varchar(20),
	FOREIGN KEY (EMPId) REFERENCES EMP_PERSONAL(EMPId),
	FOREIGN KEY (PAYId) REFERENCES GRADE_PAY(PAYId))
ALTER TABLE EMP_SALARY
ADD ACC_NO INT FOREIGN KEY REFERENCES EMP_ACCOUNT(ACC_NO)
GO

CREATE TABLE AIRPORT_EMP(
	EMPID INT PRIMARY KEY,
	DEPTID INT,
	DESIGNATION_ID INT,
	AirportId INT,
	FOREIGN KEY (EMPID) REFERENCES EMP_PERSONAL(EMPID),
	FOREIGN KEY (DEPTID) REFERENCES DEPARTMENT(DEPTID),
	FOREIGN KEY (DESIGNATION_ID) REFERENCES DESIGNATION(DESIGNATION_ID),
	FOREIGN KEY (AirportId) REFERENCES AIRPORT(AirportId))

GO
